"""empty message

Revision ID: 2b49bd803449
Revises: 279c188391a9
Create Date: 2021-11-23 19:30:57.798815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b49bd803449'
down_revision = '279c188391a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('copies', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('borrowed_copies', sa.Integer(), nullable=False))
    op.drop_column('books', 'is_loaned')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_loaned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('books', 'borrowed_copies')
    op.drop_column('books', 'copies')
    # ### end Alembic commands ###
