"""empty message

Revision ID: 0ee5ae1dc839
Revises: 34f25e3b48f4
Create Date: 2021-11-14 18:04:20.924566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee5ae1dc839'
down_revision = '34f25e3b48f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('authors', sa.Column('date_of_death', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'date_of_death')
    op.drop_column('authors', 'date_of_birth')
    # ### end Alembic commands ###
