"""empty message

Revision ID: 279c188391a9
Revises: 46b7e06449a9
Create Date: 2021-11-22 20:22:32.439350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279c188391a9'
down_revision = '46b7e06449a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
