"""empty message

Revision ID: 34f25e3b48f4
Revises: aa3b08af84eb
Create Date: 2021-11-13 20:56:00.044772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f25e3b48f4'
down_revision = 'aa3b08af84eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
