"""empty message

Revision ID: 44ea84fc30fa
Revises: 57ab1e27e03c
Create Date: 2021-12-04 12:45:40.892233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ea84fc30fa'
down_revision = '57ab1e27e03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_clients', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('books_clients', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books_clients', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books_clients', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_clients', type_='foreignkey')
    op.drop_constraint(None, 'books_clients', type_='foreignkey')
    op.drop_column('books_clients', 'client_id')
    op.drop_column('books_clients', 'book_id')
    # ### end Alembic commands ###
