"""empty message

Revision ID: 57ab1e27e03c
Revises: 464ebef37a6f
Create Date: 2021-12-04 12:42:35.246297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ab1e27e03c'
down_revision = '464ebef37a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_clients_client_id_fkey', 'books_clients', type_='foreignkey')
    op.drop_constraint('books_clients_book_id_fkey', 'books_clients', type_='foreignkey')
    op.drop_column('books_clients', 'book_id')
    op.drop_column('books_clients', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_clients', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('books_clients', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_clients_book_id_fkey', 'books_clients', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('books_clients_client_id_fkey', 'books_clients', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
