"""empty message

Revision ID: 6191f80bf8e0
Revises: b7a2cbf3692f
Create Date: 2021-11-18 19:54:54.901822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6191f80bf8e0'
down_revision = 'b7a2cbf3692f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('clients', 'phone_number',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'phone_number',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
