"""empty message

Revision ID: 626c8e9f12ee
Revises: 44ea84fc30fa
Create Date: 2021-12-04 13:12:09.811952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626c8e9f12ee'
down_revision = '44ea84fc30fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_clients_client_id_fkey', 'books_clients', type_='foreignkey')
    op.drop_constraint('books_clients_book_id_fkey', 'books_clients', type_='foreignkey')
    op.create_foreign_key(None, 'books_clients', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'books_clients', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_clients', type_='foreignkey')
    op.drop_constraint(None, 'books_clients', type_='foreignkey')
    op.create_foreign_key('books_clients_book_id_fkey', 'books_clients', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('books_clients_client_id_fkey', 'books_clients', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
