"""empty message

Revision ID: a93891df936d
Revises: 891c62855927
Create Date: 2021-11-23 20:15:02.110663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93891df936d'
down_revision = '891c62855927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'borrowed_copies',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'borrowed_copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'copies',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
