"""empty message

Revision ID: b7a2cbf3692f
Revises: a7ca4c716701
Create Date: 2021-11-18 19:52:38.757274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a2cbf3692f'
down_revision = 'a7ca4c716701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('phone_number', sa.String(length=9), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'phone_number')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
